export interface AuthResponse {
    access_token: string;
    expires_in: number;
    scope: string;
    refresh_token: string;
    token_type: string;
}

export enum CountryCode {
    FR = 'FR',
    DE = 'DE',
    IT = 'IT',
}

interface Address {
    id?: string; // generated by the server
    key?: string; // min: 2, max: 256, ^[A-Za-z0-9_-]+$
    country: CountryCode;
    streetName: string;
    postalCode: string;
    city: string;
}

export interface Customer {
    key?: string; // min: 2, max: 256, ^[A-Za-z0-9_-]+$
    customerNumber?: string;
    email: string;
    password: string;
    firstName: string;
    lastName: string;
    dateOfBirth: string;
    addresses: Address[];
    defaultShippingAddress: number;
    defaultBillingAddress: number;
}

export interface CreateCustomerResponse {
    customer: Customer;
    cart?: string;
}
